# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

tutorial: true

enable:
  retrieve: false        # don’t download from Zenodo
  retrieve_databundle: true
  build_cutout: true     # build cutout via CDS API
  drop_leap_day: true    # remove Feb 29 if present

run:
  name: "test-elec-H2"
  disable_progressbar: true
  shared_resources:
    policy: false
  shared_cutouts: true

scenario:
  clusters:
    - 5
  opts:
    - ''

countries: ['BE']

snapshots:
  start: "2013-05-01"
  end:   "2013-05-31"

electricity:
  co2limit_enable: true
  co2limit: 100.e+6

  extendable_carriers:
    Generator:   [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT, nuclear]
    StorageUnit: [battery]
    Store:       [H2]            # ← H₂‐store
    Link:        [H2 pipeline]   # ← H₂‐pipeline

  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
  estimate_renewable_capacities:
    enable: true
    from_gem: true
    year: 2020
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV:       solar

atlite:
  default_cutout: be-05-2013-era5
  cutouts:
    be-05-2013-era5:
      module: era5
      x: [4.0,  15.0]
      y: [46.0, 56.0]
      time: ["2013-05-01", "2013-05-31"]
      variables:
        - u10   # 10 m wind u-component
        - v10   # 10 m wind v-component
        - t2m   # 2 m temperature
        - si    # surface incoming shortwave

renewable:
  offwind-ac:
    max_depth: false
  offwind-dc:
    max_depth: false
  offwind-float:
    max_depth: false
    min_depth: false

clustering:
  exclude_carriers: ["OCGT", "offwind-ac", "coal"]
  temporal:
    resolution_elec: 24h

lines:
  dynamic_line_rating:
    activate: true
    max_line_rating: 1.3

solving:
  solver:
    name: highs
    options: highs-simplex
  check_infeasibility:
    enable: false      # remove any Gurobi‐only steps
  check_objective:
    enable: false

postprocess:
  summary:
    cost_threshold: 0

shipdensity:
  raster:
    activate: false

plotting:
  nice_names: {}       # avoid missing-key errors
  tech_colors: {}
  power_network_clustered:
    activate: false


