tutorial: false
enable:
  retrieve: false        # don’t download from Zenodo
  retrieve_databundle: true
  build_cutout: true     # build cutout via CDS API
  drop_leap_day: true    # remove Feb 29 if present

run:
  name: "{run_name}"  # ← dynamically set, e.g., de-2020-H2
  disable_progressbar: true
  shared_resources:
    policy: false
  shared_cutouts: true

scenario:
  clusters:
    - 5
  opts:
    - ''

countries: []

snapshots:
  start: "YYYY-MM-DD"
  end:   "YYYY-MM-DD"

electricity:
  co2limit_enable: true
  co2limit: 100.e+6

  extendable_carriers:
    Generator:   [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT, nuclear]
    StorageUnit: [battery]
    Store:       [H2]            # ← H₂ store
    Link:        [H2 pipeline]   # ← H₂ pipeline

  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float]
  estimate_renewable_capacities:
    enable: true
    from_gem: true
    year: 2020
    expansion_limit: false
    technology_mapping:
      Offshore: offwind-ac
      Onshore: onwind
      PV:       solar

atlite:
  default_cutout: placeholder
  cutouts:
    placeholder:
      module: era5
      x: [0.0, 0.0]  # placeholder values
      y: [0.0, 0.0]
      time: ["YYYY-MM-DD", "YYYY-MM-DD"]
      variables:
        - u10
        - v10
        - t2m
        - si

renewable:
  offwind-ac:
    max_depth: false
  offwind-dc:
    max_depth: false
  offwind-float:
    max_depth: false
    min_depth: false

clustering:
  exclude_carriers: ["OCGT", "offwind-ac", "coal"]
  temporal:
    resolution_elec: 24h

lines:
  dynamic_line_rating:
    activate: true
    max_line_rating: 1.3

solving:
  solver:
    name: highs
    options: highs-simplex
  check_infeasibility:
    enable: false
  check_objective:
    enable: false

postprocess:
  summary:
    cost_threshold: 0

shipdensity:
  raster:
    activate: false

plotting:
  nice_names: {}
  tech_colors: {}
  power_network_clustered:
    activate: false
